# Generated by Django 4.2.6 on 2023-10-30 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=30)),
                ('haslo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Znajomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idOsoba2', models.CharField(max_length=30)),
                ('idOsoba1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.uzytkownicy')),
            ],
        ),
        migrations.CreateModel(
            name='Listy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=50)),
                ('opis', models.CharField(max_length=300)),
                ('dataStworzenia', models.DateField(auto_now_add=True)),
                ('loginWlasciciel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.uzytkownicy')),
            ],
        ),
        migrations.CreateModel(
            name='DaneUzytkownicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('plec', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], default='1', max_length=20)),
                ('zdjProfilu', models.ImageField(upload_to='uploads/')),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.uzytkownicy')),
            ],
        ),
    ]
