# Generated by Django 4.2.6 on 2023-11-01 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prezent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=254)),
                ('loginRezerwacji', models.IntegerField()),
                ('idListy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.listy')),
            ],
        ),
    ]
